### ISSUE TITLE
求解答报错

### ISSUE THREAD

**Issue by BeiYil** [shixiangkuangmo/meituan#7]
ReferenceError: Blob is not defined
    at bJ (/ql/scripts/mt/mt.js:3362:55)
    at c (/ql/scripts/mt/mt.js:3367:44)
    at c (/ql/scripts/mt/mt.js:6666:80)
    at c (/ql/scripts/mt/mt.js:6667:78)
一直提示这个，求大佬解答

**Comment by shixiangkuangmo** [comment]
路由器搭建的青龙？

**Comment by BeiYil** [comment]
服务器啊，我看好几个人也报这个错，但是不知道怎么解决

**Comment by shixiangkuangmo** [comment]
> 服务器啊，我看好几个人也报这个错，但是不知道怎么解决

最新版本的青龙吗

**Comment by BeiYil** [comment]
不是最新版，难道要最新版？
是不是缺了什么文件？
我把所有js和json都上传了
